### ISSUE TITLE
Typescript - NPM

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#16]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/guide/typescript.md?plain=1#L9-L13

**Comment by SpookyJelly** [comment]
안녕하세요. 좋은 프로젝트 추진해주셔서 감사합니다. 해당 이슈와 #13 이슈 같이 번역하고 싶습니다
