### ISSUE TITLE
스타일 가이드

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#17]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/style-guide/index.md?plain=1#L12

**Comment by Hyokiz** [comment]
May I try to translate this issue?

**Comment by Bogyie** [comment]
Sure!

**Comment by Bogyie** [comment]
> May I try to translate this issue?

Sure!
