### ISSUE TITLE
스타일 가이드 - v-for 에 key 지정 - 자세한 설명

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#18]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/style-guide/index.md?plain=1#L273-L275

**Comment by oju0** [comment]
May I translate this?

**Comment by Bogyie** [comment]
> May I translate this?

Sure! Thanks 😊
