### ISSUE TITLE
스타일 가이드 - v-if와 v-for를 동시에 사용하지 마세요 - 자세한 설명

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#19]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/style-guide/index.md?plain=1#L325-L407

**Comment by Mccreate** [comment]
May I translate this? 👀

**Comment by Bogyie** [comment]
Sure!
