### ISSUE TITLE
스타일 가이드 - 컴포넌트 스타일 스코프

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#20]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/style-guide/index.md?plain=1#L469-L475

**Comment by YeJinHong** [comment]
May I try this?

**Comment by Bogyie** [comment]
> May I try this?

Sure! It's all yours. ;D
