### ISSUE TITLE
스타일 가이드 - 템플릿에서 컴포넌트 이름 규칙 지정(casing)

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#30]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/style-guide/index.md?plain=1#L1062-L1074

**Comment by Mccreate** [comment]
May I translate this? 🤷‍♂️

**Comment by Bogyie** [comment]
> May I translate this? 🤷‍♂️

Sure! It's all yours.
