### ISSUE TITLE
스타일 가이드 - JS/JSX에서 컴포넌트 이름 규칙 지정(casing)

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#31]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/style-guide/index.md?plain=1#L1118-L1134

**Comment by Mccreate** [comment]
May I translate this with https://github.com/ssafy-vue/kr.vuejs.org/issues/30 ? 😀

**Comment by Bogyie** [comment]
> May I translate this with #30 ? 😀

Sure! It's all yours.
