### ISSUE TITLE
스타일 가이드 - 속성 값에 따옴표

### ISSUE THREAD

**Issue by Bogyie** [ssafy-vue/kr.vuejs.org#37]
https://github.com/ssafy-vue/kr.vuejs.org/blob/6df59ee23a7a90de973600aeab1dc2cf7afb53e2/src/v2/style-guide/index.md?plain=1#L1403-L1407

**Comment by Mccreate** [comment]
제가 번역해도 될까요? 👀

**Comment by Bogyie** [comment]
It's all yours. Thank you. 😄

**Comment by Bogyie** [comment]
> 제가 번역해도 될까요? 👀

It's all yours. Thank you. 😄
