### ISSUE TITLE
스타일 가이드 - 베이스 컴포넌트 이름 [문단 삭제]

### ISSUE THREAD

**Issue by YeJinHong** [ssafy-vue/kr.vuejs.org#51]
https://github.com/ssafy-vue/kr.vuejs.org/blob/5413f533a43f41d0781e3dd0e2a84a9813a2b7a5/src/v2/style-guide/index.md?plain=1#L775-L789

I found deleted paragraph compare to https://v2.vuejs.org/v2/style-guide/

**Comment by Bogyie** [comment]
move to #25
